name: Wordlist Workflow
on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test:run

      - name: Run tests with coverage
        run: npm run test:coverage

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ github.run_number }}
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files-${{ github.run_number }}
          path: dist/

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production..."
          echo "✅ Deployment completed successfully!"
